apps:
  app2:
    image: node
    command: node app1.js
    volumes:
      - ./:/app
    depends_on:
      - mongo2
    environment:
      MONGO_ADDRESS: "$MONGO_HOST:27017"
      FOO: 1
      BAR: true
      BAZ: 4
  mongo2:
    image: mongo:3.2
    depends_on:
      - mongo
    ports:
      - 27017:27019
    ready:
      #wait_for_log: waiting for connections on port 27017
      wait_for_ports: true
    export:
      MONGO2_HOST: $DOCKER_IP
  mongo:
    image: mongo:3.2
    depends_on:
      - foo
    ports:
      - 27017:27018
    ready:
      #wait_for_log: waiting for connections on port 27017
      wait_for_ports: true
    export:
      MONGO_HOST: $DOCKER_IP

  # mongo2:
  #   image: mongo
  #   depends_on: [ mongo ]
  #   triggers:
  #     ready: waiting for connections on port 27017
  # # app-abc:
  # #   command: node app1.js
  # app3:
  #   image: node
  #   command: node app1.js
  #   environment:
  #     BAR: 1
  #     PATH: /dupa:$PATH
  #   dupa:
  #     - PATH=/dupa:$PATH
  #   depends_on:
  #     - mongo
  #     - mongo2
  # app1-nod:
  #   image: node
  #   command: node app1.js
  # app1-nod-2:
  #   image: node
  #   command: node app1.js
  #   depends_on: [ mongo ]
  #   ports:
  #     - 8090:8091/tcp
  #   volumes:
  #     - ./:/app
  # redis:
  #   image: redis