apps:
  # app-abc:
  #   command: node app1.js
  app2:
    command: node app3.js
  app3:
    image: node99999999999
    command: node app3.js
  # app1-nod:
  #   image: node
  #   command: node app1.js
  # app1-nod-2:
  #   command: node app2.js
  # redis:
  #   image: redis
  # mongo:
  #   image: mongo